Part of course work Data Analytics for cyber security 

<h2>Getting Started with PyTorch</h2>

The tutorial at [pytorch.org](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py) is also helpful. This hits the highlights of that tutorial and others.

<h3>Creating a Tensor (PyTorch matrix)</h3>
Below, we will create an unintialized Tensor. Note it has garbage values (unlike Java that initializes to 0). This saves time, but you need to be careful.

In [ ]:
import torch

x = torch.empty(4,2)
print(x)

tensor([[5.3429e+17, 9.2626e-43],
        [5.4228e+17, 9.2626e-43],
        [5.3431e+17, 9.2626e-43],
        [5.4229e+17, 9.2626e-43]])


This will initialize with all zeros, using the torch long datatype (a 64 bit integer). We might also use torch.double for a 64 bit float

In [ ]:
x=torch.zeros(4,2,dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


Or we could throw in random numbers

In [ ]:
x=torch.rand(4,2)
print(x)

tensor([[0.1185, 0.8482],
        [0.0846, 0.4136],
        [0.9388, 0.5304],
        [0.5891, 0.6329]])


We can also create tensors from numpy arrays. Note how the numpy array and the tensor share the same memory.

In [ ]:
import numpy as np
y=np.array([[1, 2, 3], [4, 5, 6]])
print(y)
z=torch.from_numpy(y)
print(z)
y[1,2]=23
print(z)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
tensor([[ 1,  2,  3],
        [ 4,  5, 23]], dtype=torch.int32)


Now let's copy the Tensor over to the GPU

In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    onGpu=z.to(device)
    print(onGpu)
else:
    print("no CUDA for you!")

no CUDA for you!
